[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_interact = "EZi3sKTYVbuCAWDq81fFC1pvTTSGy8SUbMVuQn9DGiYF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sparqxi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
